blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.com/users/572173428086538270
    about: Reach out to me on Discord.
  - name: Kotlin Documentation
    url: https://kotlinlang.org/docs/js-interop.html
    about: View Kotlin/JS documentation.