name: Report a Bug
description: Report a Bug.
labels: ['unconfirmed bug']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please take time to fill out the information below.
  - type: dropdown
    attributes:
      label: Bug Type
      description: What type of bug are you trying to report?
      multiple: true
      options:
        - Compatibility Issues
        - Console Errors
        - Incorrect Documentation
        - Kotlin Compiler Error
        - Missing Features
        - Performance Issues
        - Other Unexpected Behavior
    validations:
      required: true

  - type: input
    attributes:
      label: Tykon Version
      description: What version of Tykon are you using?
      placeholder: |
        Ex: "1.0.0"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      placeholder: |
        Ex: "Kotlin Compiler Error"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What you expect the library to do.
      placeholder: |
        Ex: "Should transpile correctly"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: What does the library do? What are the error messages shown?
      placeholder: |
        Ex: "Syntax error: unexpected '}'"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        In the box below, you can attach any relevant info or files that may help us solve the bug.
        If you think this issue is relevant to any other issues, please mention it here.
  - type: textarea
    attributes:
      label: Additional Information
      description: Any additional information that may help us solve the bug.
      placeholder: |
        Ex: "Tested on Windows 10"
    validations:
      required: false