name: Build Project

on:
  push:
    branches: [ master, ver/* ]
  pull_request:
    branches: [ master, ver/* ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Project

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: oven-sh/setup-bun@v2
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Run Tests
        run: bun run test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy TSDoc
  
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: oven-sh/setup-bun@v2
    - name: Install Dependencies
      run: bun install --frozen-lockfile
    - name: Generate TSDoc
      run: bun run doc
    - name: Deploy to GitHub Pages
      if: ${{ github.event_name != 'pull_request' && github.ref_name == 'master' }}
      run: bash tsdoc.sh ${GITHUB_SHA::7}